### ISSUE TITLE
Chessboard doesn't render at all.

### ISSUE THREAD

**Issue by lyuben-todorov** [ruilisi/react-chessground#11]
Using a default, unejected, CRA project, I'm unable to get this to render. To reproduce simply get a CRA project and copy/paste the code under installation. My App.js: 
```javascript
import Chessground from 'react-chessground'
import 'react-chessground/dist/styles/chessground.css'
import React from 'react';

export default class App extends React.Component {
  render () {
    return <Chessground />
  }
}
```
my index.js:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

```
This is how the page looks like:
![localhost_3000_](https://user-images.githubusercontent.com/14041456/72518440-aaf85b00-3855-11ea-8e3d-da7323995e74.png)

**Comment by lyuben-todorov** [comment]
Then I saw that the npm package hasn't been updated for 2 years?

**Comment by hophacker** [comment]
We will fix that.

**Comment by hophacker** [comment]
Have you installed and applied `style-loader` in webpack?

**Comment by hophacker** [comment]
Hi, friend, we have fixed that issue due the upstream changes in its css class names made by `chessground`. Pls upgrade `react-chessground` to `V1.1.0`. BTW, we have also upgraded all dependency modules to latest versions.

**Comment by lyuben-todorov** [comment]
Thanks for the update! Styles seem to be doing fine, however the board is still broken. This is what I'm getting from the example after I updated it's dependencies:
![localhost_3000_ (2)](https://user-images.githubusercontent.com/14041456/72683682-a3e17f00-3ad9-11ea-8e4c-5b411ef115cd.png)
I'm also getting the same situation from a CRA project:
```javascript
import React from 'react';
import logo from './logo.svg';
import './App.css';
import Chessground from 'react-chessground';
import 'react-chessground/dist/styles/chessground.css'
function App() {
  return (
    <div className="App">
      <Chessground
        width="38vw"
        height="38vw"
        orientation={'w'}
        turnColor={'w'}
        viewOnly={false}
        fen={"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"}
        style={{ margin: "auto" }}
        
      />    </div>
  );
}

export default App;

```
![localhost_3000_ (3)](https://user-images.githubusercontent.com/14041456/72683703-d55a4a80-3ad9-11ea-93d8-bfa1a4c69342.png)

**Comment by hophacker** [comment]
You haven't included theme.css: `import 'react-chessground/dist/assets/theme.css'

**Comment by hophacker** [comment]
Take a look at [README](./README.md)

**Comment by lyuben-todorov** [comment]
I'm still getting the same bug. When I originally encountered this I saw the 'import a theme or board won't work' warning in chessground.css so I copied chessground-theme.css from /assets and imported it as such:
```javascript
import 'react-chessground/dist/styles/chessground-theme.css'
```
![localhost_3000_ (4)](https://user-images.githubusercontent.com/14041456/72686270-1874e780-3af3-11ea-8718-0c03ae5018a0.png)
Still, theme is here but positions are messed up

**Comment by hophacker** [comment]
Have you upgraded to Version 1.1.0

**Comment by hophacker** [comment]
Hey, friend, I've just created a demo repo here using `create-create-app` https://github.com/ruilisi/react-chessground-demo.
Hope this could help you!

**Comment by lyuben-todorov** [comment]
The demo works. Thanks! I've found the culprit. The bug is symptomatic to removing
```javascript
import "react-chessground/dist/assets/chessground.css";
```
So far I was importing from `"react-chessground/dist/styles/chessground.css";` instead, which was the path instructed in the readme, so that probably needs to be updated too. Thanks for the help!

**Comment by hophacker** [comment]
Thanks for noticing that, that was fixed.

**Comment by Allirey** [comment]
had same problem with all pieces on a8 square, and only helps these imports:
`import "react-chessground/dist/assets/chessground.css"
import "react-chessground/dist/styles/chessground.css"`

**Comment by lyuben-todorov** [comment]
Have you imported `/dist/assets/theme.css`  ?

**Comment by Allirey** [comment]
previously - not, but now makes test with this import and it only changed squares on blue color, trying different combinations and works only mentioned in previous comment
